name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify_number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Check changes
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: lib/number/** test/number/**

      - name: Python
        if: steps.changed-front.outputs.changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Install oj-tool
        if: steps.changed-front.outputs.changed == 'true'
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests
        if: steps.changed-front.outputs.changed == 'true'
        run: |
          cd test/number/
          oj-verify run



  verify_data_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Check changes
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: lib/data_structure/** test/data_structure/**

      - name: Python
        if: steps.changed-front.outputs.changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Install oj-tool
        if: steps.changed-front.outputs.changed == 'true'
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests
        if: steps.changed-front.outputs.changed == 'true'
        run: |
          cd test/data_structure/
          oj-verify run
