name: ci

on:
  push: [ main ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
        
    - name: install oj-tool
      run: pip3 install -U online-judge-verify-helper
      
    - name: Run tests
      run: oj-verify all
