name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
        
    - name: install oj-tool
      run: pip3 install -U online-judge-verify-helper

    - name: check changes
      uses: marceloprado/has-changed-path@v1
      id: changed-main
      with:
        paths: lib/number/** test/number/**
      
    - name: Run tests
      run: oj-verify run test/number/**
