name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify_number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./.github/actions/
        with:
          verify-dir: 'number'



  verify_data_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./.github/actions/
        with:
          verify-dir: 'data_structure'
