name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify_number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check changes
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: lib/number/** test/number/**
      - name: Run
        if: steps.changed-front.outputs.changed == 'true'
        uses: ./.github/actions/
        with:
          verify-dir: 'number'



  verify_data_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./.github/actions/
        with:
          verify-dir: 'data_structure'
