name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
        
    - name: Install oj-tool
      run: pip3 install -U online-judge-verify-helper

    - name: Check changes
      uses: marceloprado/has-changed-path@v1
      id: changed-front
      with:
        paths: lib/number/** test/number/**
      
    - name: Run tests
      if: steps.changed-front.outputs.changed == 'true'
      run: |
        cd test/data_structure/
        oj-verify run
