name: verify

on:
  pull_request:
  push:
    paths:
      #- 'lib/**'
      #- 'test/**'

jobs:
  verify1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: ./.github/actions/setup.yml
      - name: Run tests
        run: oj-verify run test/number/**
