name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check All diff
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: lib/** test/**
      - name: Install Python
        if: steps.changed-front.outputs.changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install oj-tool
        if: steps.changed-front.outputs.changed == 'true'
        shell: bash
        run: pip3 install -U online-judge-verify-helper

      - name: Check diff for number
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: lib/number/** test/number/**
      - name: Run tests for number
        if: steps.changed-front.outputs.changed == 'true'
        run: |
          cd test/number/
          oj-verify run

      - name: Check diff for data-structure
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: lib/data_structure/** test/data_structure/**
      - name: Run tests for number
        if: steps.changed-front.outputs.changed == 'true'
        run: |
          cd test/data_structure/
          oj-verify run
